// Each row contains a picture filename, actor's name, and character role.
// Currently, the picture filenames don't exist in this project.
const castArray = [
  [ "KeanuReeves.png", "Keanu Reeves", "Neo" ],
  [ "LaurenceFishburne.png", "Laurence Fishburne", "Morpheus" ],
  [ "Carrie-AnneMoss.png", "Carrie-Anne Moss", "Trinity" ],
  [ "HugoWeaving.png", "Hugo Weaving", "Agent Smith" ],
  [ "GloriaFoster.png", "Gloria Foster", "Oracle" ],
  [ "JoePantoliano.png", "Joe Pantoliano", "Cypher" ],
  [ "MarcusChong.png", "Marcus Chong", "Tank" ],
  [ "JulianArahanga.png", "Julian Arahanga", "Apoc" ],
  [ "MattDoran.png", "Matt Doran", "Mouse" ],
  [ "BelindaMcClory.png", "Belinda McClory", "Switch" ],
  [ "AnthonyRay Parker.png", "Anthony Ray Parker", "Dozer" ],
  [ "PaulGoddard.png", "Paul Goddard", "Agent Brown" ],
  [ "RobertTaylor.png", "Robert Taylor", "Agent Jones" ],
  [ "DavidAston.png", "David Aston", "Rhineheart" ],
  [ "MarcAden Gray.png", "Marc Aden Gray", "Choi" ],
  [ "AdaNicodemou.png", "Ada Nicodemou", "Dujour (White Rabbit Girl)" ],
  [ "DeniGordon.png", "Deni Gordon", "Priestess" ],
  [ "RowanWitt.png", "Rowan Witt", "Spoon Boy" ],
  [ "EleanorWitt.png", "Eleanor Witt", "Potential" ],
  [ "TamaraBrown.png", "Tamara Brown", "Potential" ],
  [ "JanayaPender.png", "Janaya Pender", "Potential" ],
  [ "AdrynWhite.png", "Adryn White", "Potential" ],
  [ "NatalieTjen.png", "Natalie Tjen", "Potential" ],
  [ "BillYoung.png", "Bill Young", "Lieutenant" ],
  [ "DavidO'Connor.png", "David O'Connor", "FedEx Man" ],
  [ "JeremyBall.png", "Jeremy Ball", "Businessman" ],
  [ "FionaJohnson.png", "Fiona Johnson", "Woman in Red" ],
  [ "HarryLawrence.png", "Harry Lawrence", "Old Man" ],
  [ "SteveDodd.png", "Steve Dodd", "Blind Man" ],
  [ "LukeQuinton.png", "Luke Quinton", "Security Guard" ],
  [ "LawrenceWoodward.png", "Lawrence Woodward", "Guard" ],
  [ "MichaelButcher.png", "Michael Butcher", "Cop Who Captures Neo" ],
  [ "BernardLedger.png", "Bernard Ledger", "Big Cop" ],
  [ "RobertSimper.png", "Robert Simper", "Cop" ],
  [ "ChrisPattinson.png", "Chris Pattinson", "Cop (as Chris Scott)" ],
  [ "NigelHarbach.png", "Nigel Harbach", "Parking Cop" ],
  [ "MikeDuncan.png", "Mike Duncan", "Twin (uncredited)" ],
  [ "NashEdgerton.png", "Nash Edgerton", "Resistance Member (uncredited)" ],
  [ "RanaMorrison.png", "Rana Morrison", "Shaylae - Woman in Office (uncredited)" ],
  [ "SteveRutherford.png", "Steve Rutherford", "Police Officer (uncredited)" ],
  [ "CodyZacharias.png", "Cody Zacharias", "Child (uncredited)" ]
];
